export { default as Circles } from './circles.svg'
export { default as Heart } from './heart.svg'
export { default as House } from './house.svg'
export { default as Like } from './like.svg'
export { default as Medal } from './medal.svg'
export { default as Pin } from './pin.svg'
export { default as Shield } from './shield.svg'
